# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# Natural language in which you want CodeRabbit to write the review.
language: en-US

# Set the tone of reviews and chat.
# Example: 'You must use talk like Mr. T. I pity the fool who doesn't!'
tone_instructions: ''

# Enable early-access features.
early_access: true

# Enable free tier features for users not on a paid plan.
enable_free_tier: true

# Use parent settings for any values not defined here. Inheritance only
# propagates upward if enabled at each level.
inheritance: false

reviews:
  # Set the profile for reviews. Assertive profile yields more feedback,
  # that may be considered nitpicky.
  profile: assertive

  # Approve the review once CodeRabbit's comments are resolved.
  request_changes_workflow: false

  # Generate a high level summary of the changes in the PR description.
  high_level_summary: true

  # Customize the content and format of the high level summary.
  # Use 'high_level_summary_in_walkthrough' to place the summary in the
  # walkthrough instead of the description.
  high_level_summary_instructions: ''

  # Placeholder in the PR description that gets replaced with the high level
  # summary.
  high_level_summary_placeholder: '@coderabbitai summary'

  # Include the high level summary in the walkthrough comment.
  high_level_summary_in_walkthrough: false

  # Add this keyword in the PR title to auto-generate the title.
  auto_title_placeholder: '@coderabbitai'

  # Custom instructions for auto-generating the PR title.
  auto_title_instructions: ''

  # Post review details on each review.
  # Additionally, post a review status when a review is skipped in
  # certain cases.
  review_status: true

  # Post review details (ignored files, extra context used, suppressed
  # comments, etc.).
  review_details: false

  # Set the commit status to 'pending' when the review is in progress and
  #  'success' when it is complete.
  commit_status: true

  # Set the commit status to 'failure' when the PR cannot be reviewed
  # by CodeRabbit for any reason.
  fail_commit_status: false

  # Generate walkthrough in a markdown collapsible section.
  collapse_walkthrough: true

  # Generate a summary of the changed files in the walkthrough.
  changed_files_summary: true

  # Generate sequence diagrams in the walkthrough.
  sequence_diagrams: true

  # Include an estimated code review effort in the walkthrough.
  estimate_code_review_effort: true

  # Generate an assessment of how well the changes address the linked
  # issues in the walkthrough.
  assess_linked_issues: true

  # Include possibly related issues in the walkthrough.
  related_issues: true

  # Include possibly related pull requests in the walkthrough.
  related_prs: true

  # Suggest labels based on the changes in the pull request in the walkthrough.
  suggested_labels: true

  # Provide guidelines for suggesting labels for the PR.
  # When specific labels or instructions are provided, only those labels are
  # considered, though previous examples are still used to inform
  # the suggestions. If no such labels are provided, suggestions are based
  # solely on previous PRs.
  labeling_instructions: []

  # Automatically apply the suggested labels to the PR.
  auto_apply_labels: false

  # Suggest reviewers based on the changes in the pull request in
  # the walkthrough.
  suggested_reviewers: true

  # Automatically assign suggested reviewers to the pull request
  auto_assign_reviewers: false

  # Post a fortune message while the review is running.
  in_progress_fortune: true

  # Generate a poem in the walkthrough comment.
  poem: false

  # Include the 'Prompt for AI Agents' section in inline review comments to
  # provide codegen instructions for AI agents.
  enable_prompt_for_ai_agents: true

  # Specify file patterns to include or exclude in a review using glob
  # patterns (e.g., !dist/**, src/**). These patterns also apply to
  # 'git sparse-checkout', including specified patterns and ignoring excluded
  # ones (starting with '!') when cloning the repository.
  path_filters: ['!etc/lime-elements.api.md']

  # Path-specific review instructions using glob patterns to give targeted
  # guidance for matching files.
  path_instructions:
    - path: '**/*.tsx'
      instructions: >
        Our `.tsx` files are typically using StencilJS, not React. When a
        developer wants to return multiple top-level JSX elements from the
        `render` method, they will sometimes wrap them in an array literal.
        In these cases, rather than recommending they add `key` properties to
        the elements, recommend removing the hardcoded array literal. Recommend
        wrapping the elements in StencilJS's special `<Host>` element.
    - path: '**/*.{ts,tsx}'
      instructions: >
        Imports from other files in the same module (lime-elements) must use
        relative paths. Using absolute paths for imports will cause the
        production build to fail.
    - path: '**/*.{tsx,scss}'
      instructions: >
        Almost all our components use shadow-DOM. Therefore, we have no need of
        BEM-style class names in our CSS.
    - path: 'src/components/**/examples/**/*.{ts,tsx}'
      instructions: >
        These files are an exception to the rule that all imports should use
        relative paths. When these example files import something that is
        publicly exported by lime-elements, the import should be made from
        `@limetech/lime-elements`. If they import something from another file
        inside the `example` folder, the import should use a relative path.
    - path: 'src/components/**/*.tsx'
      instructions: >
        When contributors add new props to existing components in the
        lime-elements repository, they should always add documentation examples
        that demonstrate the new prop's usage and explain how it works. This
        helps with user adoption, feature discoverability, and maintains
        comprehensive documentation.

  # Abort the in-progress review if the pull request is closed or merged.
  abort_on_close: true

  # Disable caching of code and dependencies. This will force CodeRabbit to
  # download the code and dependencies fresh from the repository each time.
  disable_cache: false

  auto_review:
    # Automatic code review
    enabled: true

    # Keyword in the PR description that triggers a review when automatic
    # reviews are disabled.
    description_keyword: ''

    # Automatic incremental code review on each push
    auto_incremental_review: true

    # Pause automatic reviews after this many reviewed commits since the last
    # pause. Set to 0 to disable.
    auto_pause_after_reviewed_commits: 0

    # Ignore reviewing if the title of the pull request contains any of these
    # keywords (case-insensitive).
    ignore_title_keywords: []

    # Restrict automatic reviews to only those pull requests that match one of
    # the specified labels.
    labels: []

    # Review draft PRs.
    drafts: false

    # Base branches (other than the default branch) to review.
    # Accepts regex patterns.
    base_branches: []

    # Skip reviews for PRs authored by these usernames (exact match).
    ignore_usernames: []

  # Configure finishing touches like docstring and unit test generation
  # for PRs.
  finishing_touches:
    docstrings:
      # Allow CodeRabbit to generate docstrings for PRs.
      enabled: true

    unit_tests:
      # Allow CodeRabbit to generate unit tests for PRs.
      enabled: true

  tools:
    # Code structural search and linting using abstract syntax tree patterns.
    ast-grep:
      rule_dirs: []
      util_dirs: []
      # Use the ast-grep essentials rule package.
      essential_rules: true
      packages: []
    # Static analysis tool for finding bugs in shell scripts.
    shellcheck:
      enabled: false
    # Python linter and code formatter.
    ruff:
      enabled: false
    # Static analysis tool enforcing standards and consistency in Markdown.
    markdownlint:
      enabled: true
    # Integrates GitHub Checks into the review workflow.
    github-checks:
      enabled: true
      # Time in milliseconds to wait for all GitHub Checks to conclude.
      timeout_ms: 90000
    # Grammar, style, and spell checker supporting 30+ languages.
    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      # Only enable rules and categories specified by enabled_rules or
      # enabled_categories.
      enabled_only: false
      # Set to 'picky' to activate additional rules for formal text.
      level: default
    # Fast formatter, linter, and analyzer for web projects.
    biome:
      enabled: false
    # Dockerfile linter.
    hadolint:
      enabled: false
    # Swift code linter.
    swiftlint:
      enabled: false
    # PHP static analysis tool.
    phpstan:
      enabled: false
      # Rule level to run (0-9 or 'max'). Ignored if the config file already
      # specifies a level.
      level: default
    # PHP mess detector for identifying potential code problems.
    phpmd:
      enabled: false
    # PHP linter and coding standard checker.
    phpcs:
      enabled: false
    # Go linters aggregator and runner.
    golangci-lint:
      enabled: false
    # YAML file linter.
    yamllint:
      enabled: true
    # Secret scanner for detecting hardcoded secrets in code.
    gitleaks:
      enabled: true
    # Secret scanner with verification capabilities.
    trufflehog:
      enabled: true
    # Static analysis for infrastructure-as-code security and compliance.
    checkov:
      enabled: false
    # Terraform linter for finding potential errors and enforcing best
    # practices.
    tflint:
      enabled: false
    # Kotlin static code analyzer.
    detekt:
      enabled: false
    # Static code analysis tool for JavaScript and TypeScript.
    eslint:
      enabled: false
    # Python linter wrapping PyFlakes, pycodestyle, and McCabe.
    flake8:
      enabled: false
    # Fortran linter for code quality and style issues.
    fortitudeLint:
      enabled: false
    # Ruby static code analyzer and formatter.
    rubocop:
      enabled: false
    # Protobuf file linter.
    buf:
      enabled: false
    # Linter and language server for Rego (Open Policy Agent).
    regal:
      enabled: false
    # GitHub Actions workflow file linter.
    actionlint:
      enabled: true
    # Multi-language static code analyzer (Java, Apex, and more).
    pmd:
      enabled: false
    # Static analysis for C and C++ code.
    clang:
      enabled: false
    # Static code analysis tool for C and C++.
    cppcheck:
      enabled: false
    # High-performance static code analysis engine, compatible with Semgrep
    # configurations.
    opengrep:
      enabled: true
    # Static analysis for finding security vulnerabilities and code quality
    # issues.
    semgrep:
      enabled: true
    # CircleCI configuration file validator.
    circleci:
      enabled: false
    # Rust linter for catching common mistakes and improving code.
    clippy:
      enabled: false
    # Dialect-flexible and configurable SQL linter.
    sqlfluff:
      enabled: false
    # Security scanner for misconfigurations and secrets in IaC files.
    trivy:
      enabled: false
    # Linter for maintaining Prisma schema consistency.
    prismaLint:
      enabled: false
    # Python static code analysis tool.
    pylint:
      enabled: false
    # JavaScript and TypeScript linter written in Rust.
    oxc:
      enabled: false
    # Shopify theme linter enforcing Liquid best practices.
    shopifyThemeCheck:
      enabled: false
    # Lua code linter and static analyzer.
    luacheck:
      enabled: false
    # Ruby on Rails security vulnerability scanner.
    brakeman:
      enabled: false
    # Linter for .env files.
    dotenvLint:
      enabled: false
    # Static code analysis tool for HTML.
    htmlhint:
      enabled: true
    # Linter for stylesheets (CSS, SCSS, Sass, Less, etc.).
    stylelint:
      enabled: true
    # Makefile linter.
    checkmake:
      enabled: false
    # Vulnerability package scanning.
    osvScanner:
      enabled: false
    # Linter for Windows batch files.
    blinter:
      enabled: false
    # Static code checker for PowerShell scripts and modules.
    psscriptanalyzer:
      enabled: false
  # Pre-merge checks that must pass before merging.
  # Mode can be 'off', 'warning', or 'error' (requires resolution before
  # merging).
  pre_merge_checks:
    docstrings:
      mode: warning
      # Minimum docstring coverage (%) required to pass.
      threshold: 80
    title:
      mode: warning
      # Describe title requirements.
      requirements: ''
    description:
      mode: warning
    issue_assessment:
      mode: warning
    # Define up to 5 custom checks that must pass before merging.
    custom_checks: []

chat:
  # Generate art in chat responses (ASCII or emoji).
  art: true

  # Enable the bot to reply automatically without requiring the user to tag it.
  auto_reply: false
  integrations:
    jira:
      # Enable the Jira integration for opening issues, etc. 'auto' disables
      # the integration for public repositories.
      usage: disabled

    linear:
      # Enable the Linear integration for opening issues, etc. 'auto' disables
      # the integration for public repositories.
      usage: disabled

knowledge_base:
  # Opt out of all knowledge base features that require data retention.
  opt_out: false

  web_search:
    # Enable the web search integration.
    enabled: true

  # CodeRabbit will analyse and learn from your organization's code guidelines,
  # which you can mention in the file patterns section. These guidelines will
  # then be used to conduct thorough code reviews.
  code_guidelines:
    # Enable CodeRabbit to enforce your organization's coding standards
    # during reviews.
    enabled: true

    # Specify files for your coding guideline documents in this section.
    # CodeRabbit will scan these files to understand your team's standards and
    # apply them during code reviews.
    # Multiple files supported.
    # File names are case-sensitive.
    #
    # Common files like: (**/.cursorrules, .github/copilot-instructions.md,
    # **/CLAUDE.md, **/GEMINI.md, **/.cursor/rules/*, **/.windsurfrules,
    # **/.clinerules/*, **/.rules/*, **/AGENT.md) are included by default
    filePatterns: []

  learnings:
    # Specify the scope of learnings to use for the knowledge base.
    # 'local' uses the repository's learnings,
    # 'global' uses the organization's learnings, and
    # 'auto' uses repository's learnings for public repositories and
    # organization's learnings for private repositories.
    scope: auto

  issues:
    # Specify the scope of git platform (GitHub/GitLab) issues to use for the
    # knowledge base.
    # 'local' uses the repository's issues,
    # 'global' uses the organization's issues, and
    # 'auto' uses repository's issues for public repositories and
    # organization's issues for private repositories.
    scope: auto

  jira:
    # Enable the Jira knowledge base integration.
    # 'auto' disables the integration for public repositories.
    usage: disabled

    # Specify the Jira project keys to use for the knowledge base.
    project_keys: []

  linear:
    # Enable the Linear knowledge base integration.
    # 'auto' disables the integration for public repositories.
    usage: disabled

    # Specify the Linear team keys (identifiers) to use for the knowledge base.
    # E.g. 'ENG'
    team_keys: []

  pull_requests:
    # Specify the scope of pull requests to use for the knowledge base.
    # 'local' uses the repository's pull requests,
    # 'global' uses the organization's pull requests, and
    # 'auto' uses repository's pull requests for public repositories and
    # organization's pull requests for private repositories.
    scope: auto

  mcp:
    # Use MCP servers as a knowledge source. 'auto' disables the integration
    # for public repositories.
    usage: auto

    # Specify MCP server labels to disable (case-insensitive).
    disabled_servers: []

code_generation:
  docstrings:
    # Natural language in which you want CodeRabbit to generate docstrings.
    language: en-US

    # Provide additional guidelines for docstring generation
    # based on file paths.
    path_instructions: []

  unit_tests:
    # Provide additional guidelines for unit test generation
    # based on file paths.
    path_instructions: []

issue_enrichment:
  auto_enrich:
    # Analyze and enrich issues with additional context (related code, potential
    # solutions, complexity assessment).
    enabled: false

  planning:
    # Generate an implementation plan for issues (early preview).
    enabled: true

    auto_planning:
      # Trigger issue planning based on labels.
      enabled: true

      # Labels that control issue planning. Labels starting with '!' are
      # negative matches.
      labels: []

  labeling:
    # Define issue labels to suggest and when to suggest them.
    labeling_instructions: []

    # Automatically apply suggested labels to the issue.
    auto_apply_labels: false
