import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import { kompendium } from 'kompendium';
import guides from './guides';
import { nodeResolve } from '@rollup/plugin-node-resolve';

export const config: Config = {
    hashFileNames: false,
    namespace: 'lime-elements',
    outputTargets: [
        {
            type: 'docs-custom',
            strict: true,
            generator: kompendium({
                // Points to dist/types/index.d.ts which combines:
                // 1. components.d.ts (auto-generated by Stencil with all component prop types)
                // 2. interface.ts (manually maintained public API types)
                //
                // This config is used by `npm run docs:build` which runs a two-step build:
                // 1. Build dist with stencil.config.dist.ts (excludes examples)
                // 2. Build docs with this config (uses clean dist/types from step 1)
                //
                // This ensures production docs have all types without circular imports
                // that would occur from examples importing '@limetech/lime-elements'.
                typeRoot: './dist/types/index.d.ts',
                guides: guides,
            }),
        },
        {
            type: 'www',
            serviceWorker: null,
            dir: 'www',
            baseUrl: '/',
            copy: [
                { src: 'style/color-palette-extended.css' },
                {
                    src: '../node_modules/kompendium/dist/',
                    dest: 'assets/kompendium/',
                },
                {
                    src: 'favicon.svg',
                    dest: 'favicon.svg',
                },
            ],
        },
    ],
    plugins: [sass()],
    rollupPlugins: {
        before: [nodeResolve()],
    },
    tsconfig: './tsconfig.docs.json',
    globalStyle: 'src/global/core-styles.scss',
};
