// Allow importing a file's raw text via Vite's `?raw` query suffix (see
// https://vite.dev/guide/assets#importing-asset-as-string). This is declared
// here rather than in a standalone `.d.ts` on purpose: Stencil's `dist` output
// copies every `.d.ts` under `src/` into `dist/types/` regardless of
// `tsconfig.dist.json`'s `**/*.e2e.*` exclude, so a separate declaration file
// would ship to consumers and globally augment their own `?raw` resolution.
// Inlining it into this `.e2e.ts` file keeps it out of the published types.
declare module '*?raw' {
    const content: string;
    export default content;
}

// Read the generated declaration file as text and extract every documented
// example tag from the `@exampleComponent` doc tags. `components.d.ts` is
// regenerated by Stencil on every build, so this list stays in sync as examples
// are added or removed. Using the doc tags (rather than every registered
// `limel-example-*` element) scopes the suite to the examples that are actually
// shown in the docs, and excludes internal helper components that are only ever
// composed into other examples and take required props.
import componentsDts from './components.d.ts?raw';

const TAGS = [
    ...new Set(
        [
            ...componentsDts.matchAll(
                /@exampleComponent (limel-example-[a-z0-9-]+)/g
            ),
        ].map((match) => match[1])
    ),
].sort();

// The "composite" playground examples take a `schema` prop and dereference it
// while mounting. In the docs, `kompendium-debug` injects that prop (the owner
// component's form schema) before rendering them — see its `renderComponent()`.
// We mount examples bare here, so these would crash for lack of a schema. They
// can't be covered without replicating the docs' schema injection, so the
// docs-server scenario tests (which render them through the real debug route)
// own this coverage instead. Only the composites that actually use the schema
// are listed; the others mount fine bare and are tested normally.
const REQUIRES_DOCS_SCHEMA = new Set<string>([
    'limel-example-callout-composite',
    'limel-example-chip-set-composite',
    'limel-example-date-picker-composite',
    'limel-example-file-composite',
    'limel-example-menu-composite',
    'limel-example-picker-composite',
    'limel-example-slider-composite',
    'limel-example-tooltip-composite',
]);

// Example components that legitimately log an error or warning to the console
// when they mount (as opposed to on user interaction). Keep this list small and
// document the reason for each entry. Populated from real test runs.
const EXPECTED_NOISY = new Set<string>([]);

// The icon Cache API rejects when icon URLs don't resolve in the test
// environment; the icons still render via an in-memory fallback, so this is
// harmless (see `vitest-setup-browser.ts`). The browser surfaces these as
// unhandled rejections that the test runner logs via `console.error`, passing
// the `PromiseRejectionEvent` as the first argument — so we unwrap `.reason`
// before matching. Keep the message in sync with that setup file.
const HARMLESS_MESSAGES = ["Failed to execute 'add' on 'Cache'"];

// Format a single `console.error` argument into a readable string, unwrapping
// the `.reason` of an unhandled-rejection event. For an Error we return the
// `.stack` (which in V8 leads with the name and message) rather than just the
// message: a failed mount's most useful artifact is *where* it threw, not only
// that it did.
const formatArg = (value: unknown): string => {
    const reason =
        value && typeof value === 'object' && 'reason' in value
            ? (value as PromiseRejectionEvent).reason
            : value;
    if (reason instanceof Error) {
        return reason.stack ?? reason.message;
    }
    return String((reason as { message?: string })?.message ?? reason);
};

// Stencil and the browser often spread an error across several arguments
// (`console.error('render error', error, element)`) or pass a format string, so
// we keep every argument and join them. Capturing only the first would leave a
// failure report showing a useless `"%s"` while discarding the real Error.
const formatErrorArgs = (args: unknown[]): string =>
    args.map(formatArg).join(' ');

const isHarmlessError = (args: unknown[]): boolean =>
    HARMLESS_MESSAGES.some((message) =>
        formatErrorArgs(args).includes(message)
    );

describe('documentation example components', () => {
    it('enumerates the expected number of examples', () => {
        // Guards against the test build pointing at a config that excludes
        // examples (e.g. tsconfig.dist.json) or the enumeration regex drifting,
        // either of which would silently reduce coverage to zero.
        expect(TAGS.length).toBeGreaterThan(400);
    });

    for (const tag of TAGS) {
        const requiresDocsSchema = REQUIRES_DOCS_SCHEMA.has(tag);
        const testFor = requiresDocsSchema ? it.skip : it;
        // Spell out why a test is skipped so CI output is self-documenting
        // rather than just showing a silent `skipped`.
        const title = requiresDocsSchema
            ? `${tag} mounts without errors (skipped: needs docs schema injection, covered by the docs-driven suite)`
            : `${tag} mounts without errors`;
        testFor(title, async () => {
            // Stencil routes any error thrown by a lifecycle hook to
            // `console.error` (via its `safeCall`) rather than re-throwing, and
            // the test runner logs uncaught errors and unhandled rejections the
            // same way. Wrapping `console.error` therefore captures a failed
            // mount, an async error, and anything the example logs itself.
            const consoleErrors: unknown[][] = [];
            const originalConsoleError = console.error;
            console.error = (...args: unknown[]) => {
                consoleErrors.push(args);
                originalConsoleError(...args);
            };

            const host = document.createElement('div');
            document.body.append(host);
            try {
                const element = document.createElement(tag) as HTMLElement & {
                    componentOnReady?: () => Promise<unknown>;
                };
                host.append(element);

                await customElements.whenDefined(tag);
                await element.componentOnReady?.();
                // Give lazily-loaded child components a frame to render so their
                // errors surface too.
                await new Promise((resolve) => requestAnimationFrame(resolve));

                expect(customElements.get(tag)).toBeDefined();

                const renderedSomething =
                    (element.shadowRoot?.innerHTML.trim().length ?? 0) > 0 ||
                    element.childElementCount > 0;
                expect(renderedSomething, `${tag} rendered nothing`).toBe(true);

                if (!EXPECTED_NOISY.has(tag)) {
                    const realErrors = consoleErrors
                        .filter((args) => !isHarmlessError(args))
                        .map(formatErrorArgs);
                    expect(realErrors, `${tag} logged errors`).toEqual([]);
                }
            } finally {
                host.remove();
                console.error = originalConsoleError;
            }
        });
    }
});
