on: pull_request

name: Pull Requests

jobs:
  message-check:
    name: Commitlint

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      - uses: Lundalogik/commitlint-github-action@master
