name: Create and Publish Pre-Release
on:
  push:
    branches:
      - next
      - dev
      - alpha
      - beta

jobs:
  semantic-release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: node -v && npm -v
    - run: npm ci
    - run: npm run build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic # Need an `id` for output variables
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          @semantic-release/changelog@6.0.2
          @semantic-release/git@10.0.1
          conventional-changelog-conventionalcommits@5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
        GH_USERNAME: lime-opensource
        GH_TOKEN: ${{ secrets.CREATE_RELEASE }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_ads }}
        CI: true
    - name: Trigger update in lime-crm-building-blocks
      if: steps.semantic.outputs.new_release_published == 'true' && github.ref_name == 'next'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PRIVATE_REPO_DISPATCH }}
        event-type: update-lime-elements
        repository: Lundalogik/lime-crm-building-blocks
    - name: Trigger update in lime-crm-components
      if: steps.semantic.outputs.new_release_published == 'true' && github.ref_name == 'next'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PRIVATE_REPO_DISPATCH }}
        event-type: update-lime-elements
        repository: Lundalogik/lime-crm-components
    - name: Trigger update in lime-webclient
      if: steps.semantic.outputs.new_release_published == 'true' && github.ref_name == 'next'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PRIVATE_REPO_DISPATCH }}
        event-type: update-lime-elements
        repository: Lundalogik/lime-webclient

  docs:
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_published == 'true' && github.ref_name == 'next'
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/publish-docs.yml
    with:
      version: "NEXT-${{ needs.semantic-release.outputs.new_release_version }}"
      forcePush: true
    secrets: inherit
