name: Create and Publish Pre-Release
on:
  push:
    branches:
      - next
jobs:
  semantic-release:
    name: Run Semantic Release
    if: "!contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        fetch-depth: 0
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: node -v && npm -v
    - name: npm install
      run: |
        GH_TOKEN="${{ secrets.READ_PRIVATE_GITHUB_PACKAGES }}" ./generate_npmrc.sh
        npm ci
        rm .npmrc
    - run: npm run build
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic # Need an `id` for output variables
      with:
        semantic_version: 17.3.9
        extra_plugins: |
          @semantic-release/changelog@5.0.1
          @semantic-release/git@9.0.0
          conventional-changelog-conventionalcommits@4.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
        GH_USERNAME: lime-ci
        GH_TOKEN: ${{ secrets.CREATE_RELEASE }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_ads }}
        CI: true
    - name: Trigger update in lime-crm-components
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        event-type: update-lime-elements
        repository: Lundalogik/lime-crm-components
    - name: Trigger update in lime-webclient
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.CREATE_RELEASE }}
        event-type: update-lime-elements
        repository: Lundalogik/lime-webclient
    - name: Publish docs for new release
      if: steps.semantic.outputs.new_release_published == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_USERNAME: lime-ci
        GH_EMAIL: 617355+lime-ci@users.noreply.github.com
        GH_TOKEN: ${{ secrets.CREATE_RELEASE }}
        CI: true
      run: npm run docs:publish -- --v=NEXT-${{ steps.semantic.outputs.new_release_version }} --forcePush --authorName="lime-ci" --authorEmail="617355+lime-ci@users.noreply.github.com"
