name: Docs
on:
  workflow_call:
    inputs:
      version:
        description: 'The "name" of the version to be published.'
        required: true
        type: string
      forcePush:
        description: 'Pass `true` if git push should use `--force`.'
        required: false
        default: false
        type: boolean
      buildOnly:
        description: 'Pass `true` to only build the docs, but not publish them. (Used by PR checks for dependabot and external contributors.)'
        required: false
        default: false
        type: boolean
      linkToPR:
        description: 'Pass `true` if these docs are for a pull request. A link to the docs will be posted in a comment on the PR.'
        required: false
        default: false
        type: boolean

jobs:

  publish-docs:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    - run: node -v && npm -v
    - run: npm ci
    - run: git config --global user.email "93315277+lime-opensource@users.noreply.github.com"
    - run: git config --global user.name "Lime Technologies OSS"
    - name: Publish docs
      if: inputs.buildOnly == false
      run: npm run docs:publish -- --v=${{ inputs.version }} ${{ inputs.forcePush && '--forcePush' }}
      env:
        GH_TOKEN: ${{ secrets.PUBLISH_DOCS }}
    - name: Build docs, but do not publish
      if: inputs.buildOnly
      run: npm run docs:build

  link-docs:
    if: inputs.buildOnly == false && inputs.linkToPR == true
    name: Post link to docs on PR
    needs: [publish-docs]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/pr-comment.js`);
          await script({github, context});
        github-token: ${{ secrets.GITHUB_TOKEN }}
